# Site settings
title: Yuyao's Blog
SEOTitle: Yuyao的博客 | Yuyao's Blog
header-img: img/post-bg-desk.jpg
email: antyaoyao@gmail.com
description: "越努力越幸运"
keyword: "yuyaoma, Unimelb, ComputerScience"
url: "http://Ma-Yuyao.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Ma-Yuyao/Ma-Yuyao.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一流吃货，热爱生活"
sidebar-avatar: /img/profilepicture.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# weibo_username:     username
zhihu_username:     ma-yu-yao-31
github_username:    Ma-Yuyao    
# facebook_username:  username
# jianshu_username:   username
#twitter_username:   username




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown


# 代码高亮
#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge


markdown: kramdown
kramdown:
  input: GFM                         # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: andy_tk

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 79abbe90f9c420e3aa21                            #生成的clientID
  clientSecret: 2b5837605e11a3dd0ecd81567e341b575b526803    #生成的clientSecret
  repo: Ma-Yuyao.github.io    #仓库名称
  owner: Ma-Yuyao    #github用户名
  admin: Ma-Yuyao
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 23c63872954d216f29ce1566396cbf01

# # Google Analytics
# ga_track_id: 'UA-148351284-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


Friends
friends: [
    {
        title: "TMaize's Blog'",
        href: "https://blog.tmaize.net/"
    }
]


# Native Debugging for Homepage Display
plugins: [jekyll-paginate]